### ISSUE TITLE
Still maintaining?

### ISSUE THREAD

**Issue by mvegter** [virgilvox/node-steam-controller#3]
As the title says, are you still/going to maintain the code. As it doesn't work with wired steam controller.

**Comment by virgilvox** [comment]
to be perfectly honest I forgot I wrote this.

**Comment by mvegter** [comment]
Kinda in the same boat, moved to a different package and updated that one. The issue of not supporting wired steam controller still exists but the maintaining questions is atleast for me irrelevant at this moment.
